app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from rest_framework.authtoken import views

from app.views import HomeView, IndexView, AdminHomeView, \
    DocumentAdminListView, DocumentActiveView, VerifyView
from app.views import DocumentTypeSettingQRView, DependenceListView
from app.views import DocumentTypeListView, DocumentTypeCreateView
from app.views import DocumentTypeUpdateActiveView, DocumentTypeUpdateView
from app.views import DependenceCreateView, DependenceUpdateView
from app.views import UserMailUpdateView, UserMailListView, UserMailCreateView
from app.views import UserMailActiveView, DocumentListView, DocumentCreateView
from app.views import DocumentTypeSettingQRPreviewView, DependenceActiveView
from app.views import DocumentCreateApplicationView, LogoutApplicationView
from app.views import TypeDocumentAplicationView, DocumentListApplicationView
from app.views import LoginApplicationTestPostmanView
from app.views import DownloadFileApplicationView, DocumentTypeUserMailView
from app.views import DocumentTypeUserMailActiveView


urlpatterns = [
    path('', IndexView.as_view(),
         name='index'),
    path('verify/<str:token>/', VerifyView.as_view(), name='verify'),
    path('home/', HomeView.as_view(), name='home'),
    # admin
    path('home/admin/', AdminHomeView.as_view(), name='admon'),

    # documents_type
    path('home/documents_type/', DocumentTypeListView.as_view(),
         name='documents_type'),
    path('home/documents_type/create/', DocumentTypeCreateView.as_view(),
         name='documents_type_create'),
    path('home/documents_type/<int:pk>/update/',
         DocumentTypeUpdateView.as_view(),
         name='documents_type_update'),
    path('home/documents_type/<int:pk>/setting_qr/',
         DocumentTypeSettingQRView.as_view(),
         name='documents_type_setting_qr'),
    path('home/documents_type/<int:pk>/setting_qr_preview/',
         DocumentTypeSettingQRPreviewView.as_view(),
         name='documents_type_setting_qr_preview'),
    path('home/documents_type/<int:pk>/active/',
         DocumentTypeUpdateActiveView.as_view(),
         name='documents_type_update_active'),
    # dependences
    path('home/dependences/', DependenceListView.as_view(),
         name='dependences'),
    path('home/dependences/create/', DependenceCreateView.as_view(),
         name='dependences_create'),
    path('home/dependences/<int:pk>/update/',
         DependenceUpdateView.as_view(),
         name='dependences_update'),
    path('home/dependences/<int:pk>/active/',
         DependenceActiveView.as_view(),
         name='dependences_update_active'),
    # allowed users
    path('home/allowed_users/', UserMailListView.as_view(),
         name='allowed_users'),
    path('home/allowed_users/create/', UserMailCreateView.as_view(),
         name='allowed_user_create'),
    path('home/allowed_users/<int:pk>/update/',
         UserMailUpdateView.as_view(),
         name='allowed_user_update'),
    path('home/allowed_users/<int:pk>/active/',
         UserMailActiveView.as_view(),
         name='allowed_user_update_active'),
    path('home/allowed_users/<int:user>/documet_types/',
         DocumentTypeUserMailView.as_view(),
         name='allowed_user_docs_type'),
    path('home/allowed_users/<int:user>/documet_types/<int:pk>/active/',
         DocumentTypeUserMailActiveView.as_view(),
         name='allowed_user_docs_type_active'),


    # logout_then_login
    path('logout/', LogoutView.as_view(), name='logout'),

    # documents
    # administrador
    path('home/documents_admin/', DocumentAdminListView.as_view(),
         name='documents_admin'),
    path('documents/admin/<int:pk>/active/', DocumentActiveView.as_view(),
         name='documents_update_active'),
    # administrativos
    path('documents/', DocumentListView.as_view(), name='documents_home'),
    path('document_create/', DocumentCreateView.as_view(),
         name='document_create'),

    # aplications v1
    path('aplication/v1/login/', views.obtain_auth_token),
    path('aplication/v1/login_t/', LoginApplicationTestPostmanView.as_view(),
         name='login_rest'),
    path('aplication/v1/logout/', LogoutApplicationView.as_view(),
         name='logout_rest'),

    path('application/v1/type_document_list/',
         TypeDocumentAplicationView.as_view(), name='list_document_type_rest'),
    path('application/v1/document_create/',
         DocumentCreateApplicationView.as_view(),
         name='create_document _rest'),
    path('application/v1/document_list/',
         DocumentListApplicationView.as_view(), name='list_document_rest'),
    path('application/v1/document/<int:pk>/download/',
         DownloadFileApplicationView.as_view(), name=''),

]

verifydocs/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path(r'', include('app.urls')),
    # path(r'', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from gdstorage.storage import GoogleDriveStorage
from django.core.validators import EmailValidator
from app.validators import validate_domainonly_email
from django.contrib.auth.models import User

# Define Google Drive Storage
gd_storage = GoogleDriveStorage()
# Create your models here.


class Dependence(models.Model):
    name = models.CharField(max_length=255, verbose_name='Nombre', unique=True)
    active = models.BooleanField(default=True, verbose_name='Activo')

    updated = models.DateTimeField(auto_now=True,
                                   verbose_name='Última modificación')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Creado')

    class Meta:
        verbose_name = 'Dependencia'
        verbose_name_plural = 'Dependencias'
        ordering = ('name',)
        db_table = 'verifydocs_dependence'

    def update_active(self):
        self.active = not self.active
        self.save()

    def __str__(self):
        return self.name.capitalize()


class DocumentType(models.Model):
    CHOICES_SCALE = (
        (42, '1x'),
        (63, '1.5x'),
        (84, '2x'),
    )
    name = models.CharField(max_length=45, unique=True)
    days_validity = models.IntegerField(default=None, null=True, blank=True)
    active = models.BooleanField(default=True)
    dependence = models.ForeignKey(Dependence, on_delete=models.PROTECT,
                                   verbose_name='Dependencia', null=True,
                                   blank=True,
                                   related_name='dependence_docs_type')
    pos_x = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    pos_y = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    scale = models.IntegerField(choices=CHOICES_SCALE, default=42)
    updated = models.DateTimeField(auto_now=True,
                                   null=False,
                                   verbose_name='Última modificación')
    created = models.DateTimeField(auto_now_add=True,
                                   null=False,
                                   verbose_name='Creado')

    def update_active(self):
        self.active = not self.active
        self.save()

    class Meta:
        verbose_name = 'Tipo de documento'
        verbose_name_plural = 'Tipos de documento'
        ordering = ('name',)
        db_table = 'verifydocs_document_type'

    def __str__(self):
        return self.name.capitalize()


class UserMail(models.Model):
    ROLES_CHOICE = (
        (1, 'Administrador'),
        (2, 'Administrativo'),
        (3, 'Aplicación'),
    )
    email = models.EmailField(
        validators=[validate_domainonly_email, ],
        unique=True, verbose_name='Correo')
    role = models.IntegerField(choices=ROLES_CHOICE, null=True,
                               verbose_name='Rol')
    active = models.BooleanField(default=True,
                                 verbose_name='Activo')

    updated = models.DateTimeField(auto_now=True,
                                   verbose_name='Última modificación')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Creado')
    password = models.CharField('Contraseña', max_length=128, null=True,
                                blank=True)

    class Meta:
        verbose_name = 'Correo permitido'
        verbose_name_plural = 'Correos permitidos'
        ordering = ('-updated',)
        db_table = 'verifydocs_user_email'

    def __str__(self):
        return self.email

    def update_active(self):
        self.active = not self.active
        self.save()
        try:
            user = User.objects.get(username=self.email)
            user.is_active = self.active
            user.save()
        except User.DoesNotExist:
            pass

    def get_dependence_name(self):
        u_docs_type = self.user_doc_types_user_mail.all()
        for u_doc_type in u_docs_type:
            if not u_doc_type.active:
                continue
            doc_type = u_doc_type.document_type
            if not doc_type.active:
                continue
            return doc_type.dependence.name
        return 'Sin dependencia'


class DocumentTypeUserMail(models.Model):
    document_type = models.ForeignKey(DocumentType, on_delete=models.PROTECT,
                                      verbose_name='Tipo de documento de usuario',
                                      null=False, blank=False,
                                      related_name='doc_types_user_mail')
    usermail = models.ForeignKey(UserMail, on_delete=models.PROTECT,
                                 verbose_name='Usuario',
                                 null=False, blank=False,
                                 related_name='user_doc_types_user_mail')
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now=True,
                                   null=False,
                                   verbose_name='Última modificación')
    created = models.DateTimeField(auto_now_add=True,
                                   null=False,
                                   verbose_name='Creado')

    def update_active(self):
        self.active = not self.active
        self.save()

    class Meta:
        verbose_name = 'Tipo de documento de usuario'
        verbose_name_plural = 'Tipos de documento de usuarios'
        ordering = ('-created',)
        unique_together = (('document_type', 'usermail'),)
        db_table = 'verifydocs_user_doc_type'

    def __str__(self):
        return f'{self.document_type.name.capitalize()}'


class Document(models.Model):
    identification_applicant = models.CharField(max_length=10, null=False,
                                                blank=False)
    name_applicant = models.CharField(max_length=45, null=False, blank=False)
    email_applicant = models.EmailField(max_length=45, null=False, blank=False)
    expedition = models.DateField(null=False, blank=False)
    file_original = models.FileField(upload_to='docs_original',
                                     storage=gd_storage)

    token = models.CharField(max_length=32, null=False, blank=False,
                             unique=True)
    hash = models.CharField(max_length=64, null=False, blank=False,
                            unique=True)
    hash_qr = models.CharField(max_length=64, null=False, blank=False,
                               unique=True)
    expiration = models.DateField(null=True, blank=True, default=None)
    file_qr = models.FileField(upload_to='docs_qr', storage=gd_storage)

    created = models.DateTimeField(auto_now_add=True, verbose_name='Creado')

    doc_type_user = models.ForeignKey(DocumentTypeUserMail,
                                      null=True,
                                      on_delete=models.PROTECT,
                                      verbose_name='Tipo de documento',
                                      related_name='dependence_docs_type')
    enable = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Documento'
        verbose_name_plural = 'Documentos'
        ordering = ('-id',)
        db_table = 'verifydocs_document'

    def update_active(self):
        self.enable = not self.enable
        self.save()


class VerificationRequest(models.Model):
    verifier_name = models.CharField(max_length=128, verbose_name='Nombre')
    verifier_email = models.EmailField(verbose_name='Correo electrónico')
    token = models.CharField(max_length=32, verbose_name='Token', null=True)
    document = models.ForeignKey(Document, on_delete=models.PROTECT,
                                 verbose_name='Documento', null=True)
    end_validate_time = models.DateTimeField(verbose_name=
                                             'Fecha final para validación',
                                             null=True)
    updated = models.DateTimeField(auto_now=True,
                                   null=False,
                                   verbose_name='Última modificación')
    created = models.DateTimeField(auto_now_add=True,
                                   null=False,
                                   verbose_name='Creado')

    class Meta:
        verbose_name = 'Solicitud de verificación'
        verbose_name_plural = 'Solicitudes de verificación'
        ordering = ('-id',)
        db_table = 'verifydocs_verification_request'

    def __str__(self):
        return self.verifier_name

templates/dependence/create.html
{% extends "admin.html" %}
{% load static %}
{% block container %}
    <div class="row">
        <div class="headline-center-v2-dark col-md-12">
            <div class="shop-h1 col-md-6 col-sm-6 col-xs-6"
                style="font-size: 30px;">
                <b>
                Dependencias
                    <p class="text-success text-center">
                        {% if object.id %}
                            Actualización
                        {% else %}
                            Creación
                        {% endif %}
                    </p>
                </b>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <br>
            <p class="text-muted text-center">
                <span style="color: red">*</span> Datos requeridos para el formulario
            </p>
            <div class="row equal-height-columns margin-bottom-10">

                <div class="container">
                    <form class="form-horizontal" method="POST">
                        {% csrf_token %}
                        {{ form.active }}
                        <div class="form-group">

                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-8 col-sm-8 col-xs-12">
								<label>
									<span style="color: red">*</span> Nombre de la dependencia:
								</label>
								{{ form.name }}
								<label>
									{{ form.name.errors }}
								</label>
							</div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-8 text-right">
                                <a href="{% url 'dependences' %}" class="btn
                                btn-default">
                                    <i class="fa fa-angle-double-left"></i>
                                    Volver
                                </a>
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-floppy-o"></i>
                                    Guardar
                                </button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/dependence/list.html
{% extends "admin.html" %}
{% load static %}
{% block container %}
    <div class="row">
        <div class="headline-center-v2-dark col-md-12">
            <div class="shop-h1 col-md-6 col-sm-6 col-xs-6"
                style="font-size: 30px;"><b>Dependencias</b></div>
            <div class="col-md-6 col-sm-6 col-xs-6 text-right">
                <a class="btn btn-default"
                   style="margin-top: 14px !important;" role="button" data-toggle="modal" data-target="#exampleModal">
                    <i class="fa fa-info-circle"></i> Tutorial
                </a>
                <a class="btn btn-primary"
                   style="margin-top: 14px !important;"
                   href="{% url 'dependences_create' %}" role="button">
                    <i class="fa fa-plus"></i> Agregar
                </a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form class="form-inline" method="GET" novalidate>
                <div class="form-group">
                    {{ form_search.name }}
                </div>
                <div class="checkbox">
                    <label>
                        {{ form_search.is_active }} Solo activos
                    </label>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary" type="submit">
                        <i class="fa fa-search"></i> Buscar
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="row equal-height-columns margin-bottom-10">
                <div class="container">
                    <br>
                {% if dependence_list %}
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover text-center">
                            <thead>
                                <tr>
                                    <th class="text-center col-md-1">Creación</th>
                                    <th class="text-center col-md-1">Última modificación</th>
                                    <th class="text-center col-md-7">Nombre</th>
                                    <th class="text-center col-md-2">Gestión</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for dependence in dependence_list %}
                                <tr
                                    {% if not dependence.active %}
                                    style="background: #d0d0d0"
                                    {% endif %} >
                                    <td>{{ dependence.created|date:"SHORT_DATE_FORMAT" }}</td>
                                    <td>{{ dependence.updated|date:"SHORT_DATE_FORMAT" }}</td>
                                    <td>{{ dependence.name }}</td>
                                    <td class="text-center">
                                        <a class="btn btn-outline btn-xs btn-primary"
                                           type="button" data-toggle="tooltip"
                                           data-placement="top"
                                           title data-original-title="Editar"
                                           href="{% url 'dependences_update' dependence.id %}">
                                                <i class="fa fa-edit"></i>
                                        </a>
                                        {% if not dependence.active %}
                                            <a class="btn btn-outline btn-xs btn-primary"
                                                type="button" data-toggle="tooltip"
                                                data-placement="top"
                                                title data-original-title="Activar"
                                                href="{% url 'dependences_update_active' dependence.id %}">
                                                    <i class="fa fa-check fa-lg"></i>
                                            </a>
                                        {% else %}
                                            <a class="btn btn-outline btn-xs btn-primary"
                                                type="button" data-toggle="tooltip"
                                                data-placement="top"
                                                title data-original-title="Desactivar"
                                                href="{% url 'dependences_update_active' dependence.id %}">
                                                    <i class="fa fa-times fa-lg"></i>
                                            </a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    {% include 'includes/pagination.html' %}
                {% else %}
                    <div class="alert alert-info text-center">
                        <h3>No hay dependencias registradas en el sistema.</h3>
                    </div>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <span class="modal-title" id="exampleModalLabel" style="font-size: large">Gestionar las dependencias</span>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <iframe width="560" height="315" src="https://www.youtube.com/embed/Uylhr37cs_A" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
          </div>
        </div>
      </div>
    </div>
{% endblock %}
{% block javascript %}
    {{ block.super }}
    <script>
        $("#exampleModal").on('hidden.bs.modal', function (e) {
            $("#exampleModal iframe").attr("src", $("#exampleModal iframe").attr("src"));
        });
    </script>
{% endblock %}